$namespaces:
  s: https://schema.org/
$schemas:
- http://schema.org/version/9.0/schemaorg-current-http.rdf
baseCommand: python -m goldfinch.processes.indicator.hdd
class: CommandLineTool
cwlVersion: v1.2
hints:
  DockerRequirement:
    dockerPull: ghcr.io/bird-house/goldfinch:0.1.0
id: hdd
inputs:
  chunks:
    inputBinding:
      position: 8
      prefix: --chunks
    type: string?
  dask_maxmem:
    inputBinding:
      position: 7
      prefix: --dask-maxmem
    type: string?
  dask_nthreads:
    inputBinding:
      position: 6
      prefix: --dask-nthreads
    type: int?
  engine:
    inputBinding:
      position: 9
      prefix: --engine
    type: string?
  help:
    inputBinding:
      position: 1
      prefix: -h
    type: boolean?
  indicator:
    inputBinding:
      position: 2
      prefix: --indicator
    type:
    - symbols:
      - BEDD
      - CD
      - CDD
      - CFD
      - CSDI
      - CSU
      - CW
      - CWD
      - DTR
      - ETR
      - FD
      - GD4
      - GSL
      - HD17
      - HI
      - ID
      - P10_MeanTempWarmestQuarter
      - P11_MeanTempColdestQuarter
      - P12_AnnualPrecip
      - P13_PrecipWettestPeriod
      - P14_PrecipDriestPeriod
      - P15_PrecipSeasonality
      - P16_PrecipWettestQuarter
      - P17_PrecipDriestQuarter
      - P18_PrecipWarmestQuarter
      - P19_PrecipColdestQuarter
      - P1_AnnMeanTemp
      - P2_MeanDiurnalRange
      - P3_Isothermality
      - P4_TempSeasonality
      - P5_MaxTempWarmestPeriod
      - P6_MinTempColdestPeriod
      - P7_TempAnnualRange
      - P8_MeanTempWettestQuarter
      - P9_MeanTempDriestQuarter
      - PRCPTOT
      - R10mm
      - R20mm
      - R75p
      - R75pTOT
      - R95p
      - R95pTOT
      - R99p
      - R99pTOT
      - RR
      - RR1
      - RX1day
      - RX5day
      - SD
      - SD1
      - SD50cm
      - SD5cm
      - SDII
      - SU
      - TG
      - TG10p
      - TG90p
      - TGn
      - TGx
      - TN
      - TN10p
      - TN90p
      - TNn
      - TNx
      - TR
      - TX
      - TX10p
      - TX90p
      - TXn
      - TXx
      - WD
      - WSDI
      - WW
      - api
      - australian_hardiness_zones
      - base_flow_index
      - biologically_effective_degree_days
      - blowing_snow
      - calm_days
      - cdd
      - cddcoldTT
      - cfd
      - cffwis
      - clearness_index
      - cold_and_dry_days
      - cold_and_wet_days
      - cold_spell_days
      - cold_spell_duration_index
      - cold_spell_frequency
      - cold_spell_max_length
      - cold_spell_total_length
      - consecutive_frost_days
      - consecutive_frost_free_days
      - cool_night_index
      - cooling_degree_days
      - cooling_degree_days_approximation
      - corn_heat_units
      - cp
      - csu
      - ctmgeTT
      - ctmgtTT
      - ctmleTT
      - ctmltTT
      - ctngeTT
      - ctngtTT
      - ctnleTT
      - ctnltTT
      - ctxgeTT
      - ctxgtTT
      - ctxleTT
      - ctxltTT
      - cu
      - cwd
      - days_over_precip_doy_thresh
      - days_over_precip_thresh
      - days_with_snow
      - dc
      - ddgtTT
      - ddltTT
      - degree_days_exceedance_date
      - df
      - dlyfrzthw
      - dmc
      - doy_qmax
      - doy_qmin
      - dry_days
      - dry_spell_frequency
      - dry_spell_max_length
      - dry_spell_total_length
      - dryness_index
      - dtr
      - dtrmax
      - dtrvar
      - e_sat
      - effective_growing_degree_days
      - etr
      - ffdi
      - fg
      - fire_season
      - first_day_tg_above
      - first_day_tg_below
      - first_day_tn_above
      - first_day_tn_below
      - first_day_tx_above
      - first_day_tx_below
      - first_snowfall
      - fit
      - flow_index
      - fraction_over_precip_doy_thresh
      - fraction_over_precip_thresh
      - freezethaw_spell_frequency
      - freezethaw_spell_max_length
      - freezethaw_spell_mean_length
      - freezing_degree_days
      - freshet_start
      - frost_days
      - frost_free_season_end
      - frost_free_season_length
      - frost_free_season_start
      - frost_free_spell_max_length
      - frost_season_length
      - fxx
      - gd4
      - gddgrowTT
      - growing_degree_days
      - growing_season_end
      - growing_season_length
      - growing_season_start
      - hd17
      - hddheatTT
      - heat_index
      - heat_spell_frequency
      - heat_spell_max_length
      - heat_spell_total_length
      - heat_wave_frequency
      - heat_wave_index
      - heat_wave_max_length
      - heat_wave_total_length
      - heating_degree_days
      - heating_degree_days_approximation
      - high_flow_frequency
      - high_precip_low_temp
      - holiday_snow_and_snowfall_days
      - holiday_snow_days
      - hot_days
      - hot_spell_frequency
      - hot_spell_max_length
      - hot_spell_max_magnitude
      - hot_spell_total_length
      - huglin_index
      - humidex
      - hurs
      - hurs_fromdewpoint
      - huss
      - huss_fromdewpoint
      - ice_days
      - jetstream_metric_woollings
      - kbdi
      - last_snowfall
      - last_spring_frost
      - late_frost_days
      - latitude_temperature_index
      - liquid_precip_ratio
      - liquidprcpavg
      - liquidprcptot
      - longwave_upwelling_radiation_from_net_downwelling
      - low_flow_frequency
      - max_n_day_precipitation_amount
      - max_pr_intensity
      - maxdtr
      - maximum_consecutive_warm_days
      - mean_radiant_temperature
      - mean_temperature_from_max_and_min
      - melt_and_precip_max
      - potential_evapotranspiration
      - pp
      - prcpavg
      - prcptot
      - prlp
      - prsn
      - rain_frzgr
      - rain_season
      - rb_flashiness_index
      - return_level
      - rh
      - rprctot
      - rx1day
      - sd
      - sdii
      - sea_ice_area
      - sea_ice_extent
      - sfcWind_max
      - sfcWind_mean
      - sfcWind_min
      - sfcWindmax_max
      - sfcWindmax_mean
      - sfcWindmax_min
      - sgi
      - shortwave_upwelling_radiation_from_net_downwelling
      - snd_days_above
      - snd_max_doy
      - snd_season_end
      - snd_season_length
      - snd_season_start
      - snd_storm_days
      - snd_to_snw
      - snow_depth
      - snow_melt_we_max
      - snowfall_frequency
      - snowfall_intensity
      - snw_days_above
      - snw_max
      - snw_max_doy
      - snw_season_end
      - snw_season_length
      - snw_season_start
      - snw_storm_days
      - snw_to_snd
      - solidprcpavg
      - solidprcptot
      - spei
      - spi
      - ss
      - ssi
      - stats
      - tdps_from_huss
      - tg
      - tg10p
      - tg90p
      - tg_days_above
      - tg_days_below
      - tg_max
      - tg_mean
      - tg_min
      - thawing_degree_days
      - tmm
      - tmmax
      - tmmean
      - tmmin
      - tmn
      - tmx
      - tn
      - tn10p
      - tn90p
      - tn_days_above
      - tn_days_below
      - tn_max
      - tn_mean
      - tn_min
      - tnm
      - tnmax
      - tnmean
      - tnmin
      - tnn
      - tnx
      - tropical_nights
      - tx
      - tx10p
      - tx90p
      - tx_days_above
      - tx_days_below
      - tx_max
      - tx_mean
      - tx_min
      - tx_tn_days_above
      - txm
      - txmax
      - txmean
      - txmin
      - txn
      - txx
      - usda_hardiness_zones
      - utci
      - vDTR
      - vapor_pressure
      - vapor_pressure_deficit
      - vdtr
      - warm_and_dry_days
      - warm_and_wet_days
      - warm_spell_duration_index
      - water_budget
      - water_budget_from_tas
      - water_cycle_intensity
      - wet_prcptot
      - wet_spell_frequency
      - wet_spell_max_length
      - wet_spell_total_length
      - wetdays
      - wetdays_prop
      - wind_chill
      - wind_power_potential
      - wind_profile
      - wind_speed_from_vector
      - wind_vector_from_speed
      - windy_days
      type: enum
  input:
    type:
    - 'null'
    - inputBinding:
        position: 3
        prefix: -i
      items: string
      type: array
  output:
    inputBinding:
      position: 4
      prefix: -o
    type: string?
  verbose:
    inputBinding:
      position: 5
      prefix: -v
    type: int?
outputs:
  results:
    outputBinding:
      glob: .
    type: Directory
requirements:
  EnvVarRequirement:
    envDef: {}
  ResourceRequirement: {}
stderr: std.err
stdout: std.out
